name: Update data

on:
  schedule:
    - cron: '10 20 * * 1' # mondays at 3:10pm central (8:10pm UTC)

jobs:
  update-data:
    name: Remove data files and re-scrape data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
      - name: Install needed R packages
        run: |
          R -e "install.packages('knitr')"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip # Cache pip dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Remove old files
        run: |
          make clean
      - name: Scrape and reformat data
        run: |
          make uw_covid_2022.csv
      - name: create plots
        run: |
          make README.md
      - name: Commit new data
        run: |
          git config --local user.name "Update Action"
          git config --local user.email "actions@github.com"
          git add uw_covid_2022.csv README.md *.svg
          git commit -m 'Update data and plots' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
